export const tamilBookNames: Record<string, string> = {
  Genesis: 'ஆதியாகமம்', Exodus: 'யாத்திராகமம்', Leviticus: 'லேவியராகமம்',
  Numbers: 'எண்ணாகமம்', Deuteronomy: 'உபாகமம்', Joshua: 'யோசுவா',
  Judges: 'நியாயாதிபதிகள்', Ruth: 'ரூத்', '1 Samuel': '1 சாமுவேல்',
  '2 Samuel': '2 சாமுவேல்', '1 Kings': '1 இராஜாக்கள்',
  '2 Kings': '2 இராஜாக்கள்', '1 Chronicles': '1 நாளாகமம்',
  '2 Chronicles': '2 நாளாகமம்', Ezra: 'எஸ்றா', Nehemiah: 'நெகேமியா',
  Esther: 'எஸ்தர்', Job: 'யோபு', Psalms: 'சங்கீதம்',
  Proverbs: 'நீதிமொழிகள்', Ecclesiastes: 'பிரசங்கி',
  'Song of Songs': 'உன்னதப்பாட்டு', Isaiah: 'ஏசாயா',
  Jeremiah: 'எரேமியா', Lamentations: 'புலம்பல்', Ezekiel: 'எசேக்கியேல்',
  Daniel: 'தானியேல்', Hosea: 'ஓசியா', Joel: 'யோவேல்', Amos: 'ஆமோஸ்',
  Obadiah: 'ஒபதியா', Jonah: 'யோனா', Micah: 'மீகா', Nahum: 'நாகூம்',
  Habakkuk: 'ஆபகூக்', Zephaniah: 'செப்பனியா', Haggai: 'ஆகாய்',
  Zechariah: 'சகரியா', Malachi: 'மலாக்கி', Matthew: 'மத்தேயு',
  Mark: 'மாற்கு', Luke: 'லூக்கா', John: 'யோவான்',
  Acts: 'அப்போஸ்தலருடைய நடபடிகள்', Romans: 'ரோமர்',
  '1 Corinthians': '1 கொரிந்தியர்', '2 Corinthians': '2 கொரிந்தியர்',
  Galatians: 'கலாத்தியர்', Ephesians: 'எபேசியர்',
  Philippians: 'பிலிப்பியர்', Colossians: 'கொலோசெயர்',
  '1 Thessalonians': '1 தெசலோனிக்கேயர்',
  '2 Thessalonians': '2 தெசலோனிக்கேயர்', '1 Timothy': '1 தீமோத்தேயு',
  '2 Timothy': '2 தீமோத்தேயு', Titus: 'தீத்து', Philemon: 'பிலேமோன்',
  Hebrews: 'எபிரெயர்', James: 'யாக்கோபு', '1 Peter': '1 பேதுரு',
  '2 Peter': '2 பேதுரு', '1 John': '1 யோவான்', '2 John': '2 யோவான்',
  '3 John': '3 யோவான்', Jude: 'யூதா',
  Revelation: 'வெளிப்படுத்தின விசேஷம்',
}

export const tamilBookNamesLegacy: Record<string, string> = {
  'Genesis': 'Mjpahfkk;',
  'Exodus': 'ahj;jpuhfkk;',
  'Leviticus': 'Nytpauhfkk;',
  'Numbers': 'vz;zhfkk;',
  'Deuteronomy': 'cghfkk;',
  'Joshua': 'NahRth',
  'Judges': 'epahahjpgjpfs;',
  'Ruth': '\\&j;',
  '1 Samuel': '1 rhKNty;',
  '2 Samuel': '2 rhKNty;',
  '1 Kings': '1 ,uh[hf;fs;',
  '2 Kings': '2 ,uh[hf;fs;',
  '1 Chronicles': '1 ehshfkk;',
  '2 Chronicles': '2 ehshfkk;',
  'Ezra': 'v];wh',
  'Nehemiah': 'neNfkpah',
  'Esther': 'v];ju;',
  'Job': 'NahG',
  'Psalms': 'rq;fPjk;',
  'Proverbs': 'ePjpnkhopfs;',
  'Ecclesiastes': 'gpurq;fp',
  'Song of Songs': 'cd;djg;ghl;L',
  'Isaiah': 'Vrhah',
  'Jeremiah': 'vNukpah',
  'Lamentations': 'Gyk;gy;',
  'Ezekiel': 'vNrf;fpNay;',
  'Daniel': 'jhdpNay;',
  'Hosea': 'Xrpah',
  'Joel': 'NahNty;',
  'Amos': 'MNkh];',
  'Obadiah': 'xgjpah',
  'Jonah': 'Nahdh',
  'Micah': 'kPfh',
  'Nahum': 'eh$k;',
  'Habakkuk': 'Mg$f;',
  'Zephaniah': 'nrg;gdpah',
  'Haggai': 'Mfha;',
  'Zechariah': 'rfupah',
  'Malachi': 'kyhf;fp',
  'Matthew': 'kj;NjA',
  'Mark': 'khw;F',
  'Luke': 'Y}f;fh',
  'John': 'Nahthd;',
  'Acts': 'mg;Ngh];jyUila elgbfs;',
  'Romans': 'Nuhku;',
  '1 Corinthians': '1 nfhupe;jpau;',
  '2 Corinthians': '2 nfhupe;jpau;',
  'Galatians': 'fyhj;jpau;',
  'Ephesians': 'vNgrpau;',
  'Philippians': 'gpypg;gpau;',
  'Colossians': 'nfhNyhnrau;',
  '1 Thessalonians': '1 njrNyhdpf;Nfau;',
  '2 Thessalonians': '2 njrNyhdpf;Nfau;',
  '1 Timothy': '1 jPNkhj;NjA',
  '2 Timothy': '2 jPNkhj;NjA',
  'Titus': 'jPj;J',
  'Philemon': 'gpNyNkhd;',
  'Hebrews': 'vgpnuau;',
  'James': 'ahf;NfhG',
  '1 Peter': '1 NgJU',
  '2 Peter': '2 NgJU',
  '1 John': '1 Nahthd;',
  '2 John': '2 Nahthd;',
  '3 John': '3 Nahthd;',
  'Jude': 'A+jh',
  'Revelation': 'ntspg;gLj;jpd tpNr\\k;',
}
