// Bidirectional Tamil Unicode <-> Bamini converter (browser-side).
//
// Forward rules are the standard Unicode->Bamini mapping (derived from
// scripts/unicode-bamini.cjs, source: github.com/Pakeetharan/unicode-bamini-converter).
// Forward applies the ordered rules as sequential replacements; reverse uses a
// single-pass longest-match scan (sequential replace would cascade, e.g. a
// reversed ',' could be re-mapped by a later rule).
//
// NOTE: this is pure *standard* Bamini (the ';' slot is pulli, as church Bamini
// fonts expect). The Tharmini-specific tweaks used when rendering the Bible
// images (semicolon -> 0x40, double-matra normalize) live in the build script,
// not here, so this tool round-trips cleanly.

const RULES: ReadonlyArray<readonly [string, string]> = [
  ["ஸ்ரீ", "="],
  [",", ">"],
  ["ஜௌ", "n[s"],
  ["ஜோ", "N[h"],
  ["ஜொ", "n[h"],
  ["ஜா", "[h"],
  ["ஜி", "[p"],
  ["ஜீ", "[P"],
  ["ஜு", "[{"],
  ["ஜூ", "[_"],
  ["ஜெ", "n["],
  ["ஜே", "N["],
  ["ஜை", "i["],
  ["ஜ்", "[;"],
  ["ஜ", "["],
  ["கௌ", "nfs"],
  ["கோ", "Nfh"],
  ["கொ", "nfh"],
  ["கா", "fh"],
  ["கி", "fp"],
  ["கீ", "fP"],
  ["கு", "F"],
  ["கூ", "$"],
  ["கெ", "nf"],
  ["கே", "Nf"],
  ["கை", "if"],
  ["க்", "f;"],
  ["க", "f"],
  ["ஙௌ", "nqs"],
  ["ஙோ", "Nqh"],
  ["ஙொ", "nqh"],
  ["ஙா", "qh"],
  ["ஙி", "qp"],
  ["ஙீ", "qP"],
  ["ஙு", "*"],
  ["ஙூ", "*"],
  ["ஙெ", "nq"],
  ["ஙே", "Nq"],
  ["ஙை", "iq"],
  ["ங்", "q;"],
  ["ங", "q"],
  ["சௌ", "nrs"],
  ["சோ", "Nrh"],
  ["சொ", "nrh"],
  ["சா", "rh"],
  ["சி", "rp"],
  ["சீ", "rP"],
  ["சு", "R"],
  ["சூ", "R+"],
  ["செ", "nr"],
  ["சே", "Nr"],
  ["சை", "ir"],
  ["ச்", "r;"],
  ["ச", "r"],
  ["ஞௌ", "nQs"],
  ["ஞோ", "NQh"],
  ["ஞொ", "nQh"],
  ["ஞா", "Qh"],
  ["ஞி", "Qp"],
  ["ஞீ", "QP"],
  ["ஞு", "*"],
  ["ஞூ", "*"],
  ["ஞெ", "nQ"],
  ["ஞே", "NQ"],
  ["ஞை", "iQ"],
  ["ஞ்", "Q;"],
  ["ஞ", "Q"],
  ["டௌ", "nls"],
  ["டோ", "Nlh"],
  ["டொ", "nlh"],
  ["டா", "lh"],
  ["டி", "b"],
  ["டீ", "B"],
  ["டு", "L"],
  ["டூ", "^"],
  ["டெ", "nl"],
  ["டே", "Nl"],
  ["டை", "il"],
  ["ட்", "l;"],
  ["ட", "l"],
  ["ணௌ", "nzs"],
  ["ணோ", "Nzh"],
  ["ணொ", "nzh"],
  ["ணா", "zh"],
  ["ணி", "zp"],
  ["ணீ", "zP"],
  ["ணு", "Z"],
  ["ணூ", "Z}"],
  ["ணெ", "nz"],
  ["ணே", "Nz"],
  ["ணை", "iz"],
  ["ண்", "z;"],
  ["ண", "z"],
  ["தௌ", "njs"],
  ["தோ", "Njh"],
  ["தொ", "njh"],
  ["தா", "jh"],
  ["தி", "jp"],
  ["தீ", "jP"],
  ["து", "J"],
  ["தூ", "J}"],
  ["தெ", "nj"],
  ["தே", "Nj"],
  ["தை", "ij"],
  ["த்", "j;"],
  ["த", "j"],
  ["நௌ", "nes"],
  ["நோ", "Neh"],
  ["நொ", "neh"],
  ["நா", "eh"],
  ["நி", "ep"],
  ["நீ", "eP"],
  ["நு", "E"],
  ["நூ", "E}"],
  ["நெ", "ne"],
  ["நே", "Ne"],
  ["நை", "ie"],
  ["ந்", "e;"],
  ["ந", "e"],
  ["னௌ", "nds"],
  ["னோ", "Ndh"],
  ["னொ", "ndh"],
  ["னா", "dh"],
  ["னி", "dp"],
  ["னீ", "dP"],
  ["னு", "D"],
  ["னூ", "D}"],
  ["னெ", "nd"],
  ["னே", "Nd"],
  ["னை", "id"],
  ["ன்", "d;"],
  ["ன", "d"],
  ["பௌ", "ngs"],
  ["போ", "Ngh"],
  ["பொ", "ngh"],
  ["பா", "gh"],
  ["பி", "gp"],
  ["பீ", "gP"],
  ["பு", "G"],
  ["பூ", "G+"],
  ["பெ", "ng"],
  ["பே", "Ng"],
  ["பை", "ig"],
  ["ப்", "g;"],
  ["ப", "g"],
  ["மௌ", "nks"],
  ["மோ", "Nkh"],
  ["மொ", "nkh"],
  ["மா", "kh"],
  ["மி", "kp"],
  ["மீ", "kP"],
  ["மு", "K"],
  ["மூ", "%"],
  ["மெ", "nk"],
  ["மே", "Nk"],
  ["மை", "ik"],
  ["ம்", "k;"],
  ["ம", "k"],
  ["யௌ", "nas"],
  ["யோ", "Nah"],
  ["யொ", "nah"],
  ["யா", "ah"],
  ["யி", "ap"],
  ["யீ", "aP"],
  ["யு", "A"],
  ["யூ", "A+"],
  ["யெ", "na"],
  ["யே", "Na"],
  ["யை", "ia"],
  ["ய்", "a;"],
  ["ய", "a"],
  ["ரௌ", "nus"],
  ["ரோ", "Nuh"],
  ["ரொ", "nuh"],
  ["ரா", "uh"],
  ["ரி", "up"],
  ["ரீ", "uP"],
  ["ரு", "U"],
  ["ரூ", "\\&"],
  ["ரெ", "nu"],
  ["ரே", "Nu"],
  ["ரை", "iu"],
  ["ர்", "u;"],
  ["ர", "u"],
  ["லௌ", "nys"],
  ["லோ", "Nyh"],
  ["லொ", "nyh"],
  ["லா", "yh"],
  ["லி", "yp"],
  ["லீ", "yP"],
  ["லு", "Y"],
  ["லூ", "Y}"],
  ["லெ", "ny"],
  ["லே", "Ny"],
  ["லை", "iy"],
  ["ல்", "y;"],
  ["ல", "y"],
  ["ளௌ", "nss"],
  ["ளோ", "Nsh"],
  ["ளொ", "nsh"],
  ["ளா", "sh"],
  ["ளி", "sp"],
  ["ளீ", "sP"],
  ["ளு", "S"],
  ["ளூ", "Sh"],
  ["ளெ", "ns"],
  ["ளே", "Ns"],
  ["ளை", "is"],
  ["ள்", "s;"],
  ["ள", "s"],
  ["வௌ", "nts"],
  ["வோ", "Nth"],
  ["வொ", "nth"],
  ["வா", "th"],
  ["வி", "tp"],
  ["வீ", "tP"],
  ["வு", "T"],
  ["வூ", "T+"],
  ["வெ", "nt"],
  ["வே", "Nt"],
  ["வை", "it"],
  ["வ்", "t;"],
  ["வ", "t"],
  ["ழௌ", "nos"],
  ["ழோ", "Noh"],
  ["ழொ", "noh"],
  ["ழா", "oh"],
  ["ழி", "op"],
  ["ழீ", "oP"],
  ["ழு", "O"],
  ["ழூ", "*"],
  ["ழெ", "no"],
  ["ழே", "No"],
  ["ழை", "io"],
  ["ழ்", "o;"],
  ["ழ", "o"],
  ["றௌ", "nws"],
  ["றோ", "Nwh"],
  ["றொ", "nwh"],
  ["றா", "wh"],
  ["றி", "wp"],
  ["றீ", "wP"],
  ["று", "W"],
  ["றூ", "W}"],
  ["றெ", "nw"],
  ["றே", "Nw"],
  ["றை", "iw"],
  ["ற்", "w;"],
  ["ற", "w"],
  ["ஹௌ", "n`s"],
  ["ஹோ", "N`h"],
  ["ஹொ", "n`h"],
  ["ஹா", "`h"],
  ["ஹி", "`p"],
  ["ஹீ", "`P"],
  ["ஹு", "{`"],
  ["ஹூ", "`_"],
  ["ஹெ", "n`"],
  ["ஹே", "N`"],
  ["ஹை", "i`"],
  ["ஹ்", "`;"],
  ["ஹ", "`"],
  ["ஷௌ", "n\\s"],
  ["ஷோ", "N\\h"],
  ["ஷொ", "n\\h"],
  ["ஷா", "\\h"],
  ["ஷி", "\\p"],
  ["ஷீ", "\\P"],
  ["ஷு", "{"],
  ["ஷூ", "\\_"],
  ["ஷெ", "n\\"],
  ["ஷே", "N\\"],
  ["ஷை", "i\\"],
  ["ஷ்", "\\;"],
  ["ஷ", "\\"],
  ["ஸௌ", "n]s"],
  ["ஸோ", "N]h"],
  ["ஸொ", "n]h"],
  ["ஸா", "]h"],
  ["ஸி", "]p"],
  ["ஸீ", "]P"],
  ["ஸு", "]{"],
  ["ஸூ", "]_"],
  ["ஸெ", "n]"],
  ["ஸே", "N]"],
  ["ஸை", "i]"],
  ["ஸ்", "];"],
  ["ஸ", "]"],
  ["அ", "m"],
  ["ஆ", "M"],
  ["இ", ","],
  ["ஈ", "<"],
  ["உ", "c"],
  ["ஊ", "C"],
  ["எ", "v"],
  ["ஏ", "V"],
  ["ஐ", "I"],
  ["ஒ", "x"],
  ["ஓ", "X"],
  ["ஔ", "xs"],
  ["ஃ", "/"],
]

// Tharmini conventions (must match scripts/build_legacy.mjs):
//  - a literal ';' becomes '@' (0x40), Tharmini's semicolon glyph, because the
//    standard ';' slot (0x3b) is pulli. Done at input level so it survives the
//    rule table.
//  - the source double-matra typo  ு + ூ  is normalized to ூ.
const U = 'ு'
const UU = 'ூ'
const SEMI_GLYPH = '@'
const SEMI_SENTINEL = '' // PUA placeholder the rule table ignores

export function unicodeToBamini(text: string): string {
  text = text.split(U + UU).join(UU)
  text = text.split(';').join(SEMI_SENTINEL)
  for (const [uni, bam] of RULES) text = text.split(uni).join(bam)
  return text.split(SEMI_SENTINEL).join(SEMI_GLYPH)
}

// reverse lookup: first forward rule for a given Bamini string wins
const REV = new Map<string, string>()
let REV_MAX = 0
for (const [uni, bam] of RULES) {
  if (bam.length && !REV.has(bam)) {
    REV.set(bam, uni)
    if (bam.length > REV_MAX) REV_MAX = bam.length
  }
}
// Tharmini's '@' is a literal semicolon (not in the standard rule table).
REV.set(SEMI_GLYPH, ';')

export function baminiToUnicode(text: string): string {
  let out = ''
  let i = 0
  while (i < text.length) {
    let matched = false
    for (let L = Math.min(REV_MAX, text.length - i); L >= 1; L--) {
      const sub = text.slice(i, i + L)
      const uni = REV.get(sub)
      if (uni !== undefined) {
        out += uni
        i += L
        matched = true
        break
      }
    }
    if (!matched) {
      out += text[i]
      i++
    }
  }
  return out
}
